
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anirudh
 */
public class Purchase extends javax.swing.JFrame {

    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
            
    
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    java.util.Date dd = new java.util.Date();
    String s = sdf.format(dd);
    L1.setText(s);
    
    
    
    
    }
    
    public Purchase(TableModel tab) {
        initComponents();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date dd = new java.util.Date();
        String s = sdf.format(dd);
        L1.setText(s);
        
        
        DefaultTableModel t1 = (DefaultTableModel)tab;
        DefaultTableModel t2 = (DefaultTableModel)jTable1.getModel();
        
        while(t2.getRowCount()>0)
        {
            t2.removeRow(0);
        }
        double price=0;
        for(int i=0;i<t1.getRowCount();i++)
        {
            price+=Double.parseDouble(t1.getValueAt(i, 4).toString());
            t2.addRow(new Object[]{
            t1.getValueAt(i,0),
            t1.getValueAt(i,1),
            t1.getValueAt(i,2),
            t1.getValueAt(i,3),
            t1.getValueAt(i,4),
        });
            
        }
        T2.setText(""+price);
    
    R3.setSelected(true);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        R5 = new javax.swing.JRadioButton();
        R4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        R1 = new javax.swing.JRadioButton();
        t1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        R2 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        R3 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Purchase Tab");
        setBackground(new java.awt.Color(153, 255, 51));
        setForeground(new java.awt.Color(204, 255, 0));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("Payment Method");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 280, 50));

        R5.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(R5);
        R5.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        R5.setText("Debit Card ");
        R5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R5ActionPerformed(evt);
            }
        });
        jPanel1.add(R5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 370, 180, 50));

        R4.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(R4);
        R4.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        R4.setText("Credit Card");
        jPanel1.add(R4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 170, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Amount to be Billed");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, 240, 50));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Move to the previous page");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 440, 280, 40));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Clear List");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 150, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Artist", "Genre", "Year", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 450, 220));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Print Bill");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 190, 60));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Name of Customer");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 210, 50));

        L1.setText("Date");
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, 110, 30));

        L2.setText("Invoice: ");
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 110, 30));

        R1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(R1);
        R1.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        R1.setText("Net Banking");
        jPanel1.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 180, 50));
        jPanel1.add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 200, 40));

        T2.setEditable(false);
        T2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        T2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T2ActionPerformed(evt);
            }
        });
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 520, 210, 30));

        jButton3.setText("PRINT FORM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-110, 0, -1, 30));

        R2.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(R2);
        R2.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        R2.setText("PAYTM");
        jPanel1.add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 140, 40));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setText("Remove the Selected item");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        R3.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(R3);
        R3.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        R3.setText("Cash");
        jPanel1.add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 120, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TitleImg.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 340, 100));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Items to Purchase");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 320, 50));

        jLabel7.setText("CopyRights (2017-2042)All Rights Reserved....!!!!");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 550, 250, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Back
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // CLEAR TABLE
        DefaultTableModel model=(DefaultTableModel)
        jTable1.getModel();
        int rows=model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            model.removeRow(0);
        }
         T2.setText("");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // PrintBill
       
        if(t1.getText().equals(""))
            JOptionPane.showMessageDialog(this,"Fill all Information");
        
        else{
        
        String cust_name,dop,payment="",item="",amount,sql,invoiceno="";
               int sno=0;
       try
       { 
       Class.forName("java.sql.DriverManager");
      Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","9829");
       
       Statement st0 = con.createStatement();
       String sql0 = "Select Max(Invoiceno) from sales_m";
       ResultSet rs0 = st0.executeQuery(sql0);
       
       if(rs0.next())
       {
           invoiceno =""+ (rs0.getInt(1)+1);
           
       }
       
       
       Statement st1 = con.createStatement();
       String sql1 = "Select Max(sno) from sales_d";
       ResultSet rs1 = st1.executeQuery(sql1);
       
       if(rs1.next())
       {
           sno =rs1.getInt(1)+1;
       }
       
       cust_name=t1.getText();
       amount=T2.getText();
       dop=L1.getText();
       
       if(R1.isSelected())
           payment = R1.getText();
       else if(R2.isSelected())
           payment = R2.getText();
       else if(R3.isSelected())
           payment = R3.getText();
       else if(R4.isSelected())
           payment = R4.getText();
       else if(R5.isSelected())
           payment = R5.getText();
       
       
       Statement st2 = con.createStatement();
       String sql2="insert into sales_m  values('"+cust_name+"','"+dop+"','"+payment+"',"+amount+","+invoiceno+")";
       st2.executeUpdate(sql2);
    
       DefaultTableModel model=(DefaultTableModel)jTable1.getModel();
      
       for(int i=0;i<model.getRowCount();i++)
        {
            
            item=model.getValueAt(i,0).toString();
            String sql3="insert into sales_d values('"+ sno++ +"','"+invoiceno+"','"+item+"')";    
            Statement st=con.createStatement();
            st.executeUpdate(sql3);
        }
     
          JOptionPane.showMessageDialog(this,"Record is saved");
            
         
      }
        
        catch (Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());    
        }
   
       new InvoiceFrame(jTable1.getModel()).setVisible(true);
       dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
      String invoiceno="";
        try{ 
       Class.forName("java.sql.DriverManager");
       Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","9829");
       
       Statement st0 = con.createStatement();
       String sql0 = "Select Max(Invoiceno) from sales_m";
       ResultSet rs0 = st0.executeQuery(sql0);
       
       if(rs0.next())
       {
           invoiceno =""+ (rs0.getInt(1)+1);
           
       }
       L2.setText("InvoiceNo:"+invoiceno);
        }
        catch (Exception e)
        {
        JOptionPane.showMessageDialog(this,e.getMessage());    
        }
    
    


    }//GEN-LAST:event_formWindowActivated

    private void R5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R5ActionPerformed
        // TODO add your handling
    }//GEN-LAST:event_R5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void T2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_T2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_T2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         DefaultTableModel t1=(DefaultTableModel)jTable1.getModel();
         if(jTable1.getSelectedRowCount()==0)
             JOptionPane.showMessageDialog(this,"Please Select a row to remove");
         else
         {int SelectedRowIndex = jTable1.getSelectedRow();
          t1.removeRow(SelectedRowIndex);
         }
        double price=0;
        for(int i=0;i<t1.getRowCount();i++)
        {
          price+=Double.parseDouble(t1.getValueAt(i, 4).toString());
        }
        T2.setText(""+price);
                
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JRadioButton R1;
    private javax.swing.JRadioButton R2;
    private javax.swing.JRadioButton R3;
    private javax.swing.JRadioButton R4;
    private javax.swing.JRadioButton R5;
    private javax.swing.JTextField T2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
